const actions = {
  GET_THEATERS: 'GET_THEATERS',
  GET_THEATERS_SUCCESS: 'GET_THEATERS_SUCCESS',
  GET_THEATERS_FAILURE: 'GET_THEATERS_FAILURE',
  SET_THEATER_DRAWER_VISIBLE: 'SET_THEATER_DRAWER_VISIBLE',
  DELETE_THEATER: 'DELETE_THEATER',
  DELETE_THEATER_SUCCESS: 'DELETE_THEATER_SUCCESS',
  DELETE_THEATER_FAILURE: 'DELETE_THEATER_FAILURE',
  SET_THEATER_DETAILS: 'SET_THEATER_DETAILS',
  SEARCH_THEATER_DETAILS: 'SEARCH_THEATER_DETAILS',
  REGISTER_THEATER: 'REGISTER_THEATER',
  REGISTER_THEATER_SUCCESS: 'REGISTER_THEATER_SUCCESS',
  REGISTER_THEATER_FAILURE: 'REGISTER_THEATER_FAILURE',
  UPDATE_THEATER: 'UPDATE_THEATER',
  UPDATE_THEATER_SUCCESS: 'UPDATE_THEATER_SUCCESS',
  UPDATE_THEATER_FAILURE: 'UPDATE_THEATER_FAILURE',
  SET_ACCOUNT_DRAWER_VISIBLE: 'SET_ACCOUNT_DRAWER_VISIBLE',

};
 
export default actions;
