const actions = {
  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  SET_USER_DRAWER_VISIBLE: 'SET_USER_DRAWER_VISIBLE',
  CREATE_USER: 'CREATE_USER',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
  DELETE_USER: 'DELETE_USER',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  SEARCH_USER_DETAILS: 'SEARCH_USER_DETAILS',
  HANDLE_VIEW_TYPE: 'HANDLE_VIEW_TYPE',
};

export default actions;
